### ISSUE TITLE
drs_filename creates unncessary failures

### ISSUE THREAD

**Issue by huard** [bird-house/finch#103]
## Description

A process using drs_filename will fail if the project is not hard-coded in finch. I don't think this is reasonable. We should *try* to rename files, but if it doesn't work, still get a response. 

## Environment

* finch version used, if any: 0.4.4
* Python version, if any:

**Comment by huard** [comment]
See https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/37

**Comment by tlvu** [comment]
Direct link to relevant comment: https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/37#issuecomment-598308186

**Comment by davidcaron** [comment]
I will fix it, along with #69 and release a bug fix version.

**Comment by huard** [comment]
Thanks !

**Comment by nilshempelmann** [comment]
@davidcaron: great!
May be this helps:
https://eggshell.readthedocs.io/en/latest/_modules/eggshell/nc/nc_utils.html#drs_filename
or:
https://eggshell.readthedocs.io/en/latest/_modules/eggshell/nc/nc_utils.html#sort_by_filename

**Comment by davidcaron** [comment]
@huard @tlvu `v0.4.1` should be building in dockerhub

**Comment by huard** [comment]
Merci !
