### ISSUE TITLE
Dockerfile install finch from conda

### ISSUE THREAD

**Issue by huard** [bird-house/finch#108]
## Description

Which is problematic for testing. I suggest using the cookie-cutter version if possible.

**Comment by tlvu** [comment]
Well the Dockerfile version also sort of install from source (or litterally just copy the source and run from it, without even installing):

https://github.com/bird-house/finch/blob/f43f52206b81025fda3f9044609cce2befe88494/Dockerfile#L19

Compare to the cookie-cutter version that copy the source, then installs using `python setup.py develop`:

https://github.com/bird-house/cookiecutter-birdhouse/blob/37c609bc4942227c2a64e6386cf38a9207da9534/%7B%7Bcookiecutter.project_repo_name%7D%7D/Dockerfile#L23

**Comment by huard** [comment]
My bad. I mistook the name of the environment for a dependency.
