### ISSUE TITLE
xclim Class FIT already exists and will be overwritten

### ISSUE THREAD

**Issue by MatProv** [bird-house/finch#150]
## Description

After having started Finch via docker-compose, this error appears:

```
wps_1  | [2021-02-16 15:08:24 +0000] [1] [INFO] Starting gunicorn 20.0.4
wps_1  | [2021-02-16 15:08:24 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
wps_1  | [2021-02-16 15:08:24 +0000] [1] [INFO] Using worker: sync
wps_1  | [2021-02-16 15:08:24 +0000] [7] [INFO] Booting worker with pid: 7

wps_1  | [2021-02-16 15:10:03 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:7)
wps_1  | /opt/conda/envs/finch/lib/python3.8/site-packages/xclim/core/indicator.py:61: UserWarning: Class FIT already exists and will be overwritten.
wps_1  |   warnings.warn(f"Class {name} already exists and will be overwritten.")
wps_1  | [2021-02-16 15:10:04 +0000] [12] [INFO] Booting worker with pid: 12
```

## Environment

* Finch 0.6.1

## Steps to Reproduce

```
docker-compose build; docker-compose up -d
docker-compose logs -f
```

Will appear about 1 minute after launch, then reappear after certain interval of time.

**Comment by MatProv** [comment]
@huard I'm not sure but it's maybe related to new changes introduced in 0.6.1. 
In the past versions (eg: 0.5.2) I didn't had this warning.

**Comment by aulemahal** [comment]
If I may, I think this is related to the redeclaration of the `fit` indicator in `processes/__init__.py`. In any case, that is not problematic for xclim at all. Indicator subclass overwrites are not dangerous if we know what overwrote them!

**Comment by huard** [comment]
Exactly. I realized there was a bug in xclim, fixed it, but didn't want to wait for an xclim release to get it working in Finch, so simply redefined the indicator.

**Comment by MatProv** [comment]
Ok thanks @aulemahal and @huard for the explanation. I'll close this issue as this will get fixed in future release of xclim and is not critical.
