### ISSUE TITLE
Add models in metadata

### ISSUE THREAD

**Issue by MatProv** [bird-house/finch#157]
## Description

For CCDP, we would need to include in the metadata the models which had been used to generate an output. 
This is to ensure that the validity of the output can be validated, even if let's say there was a missing dataset.
This actually occurs for PCIC12 RCP 2.6 where we have three missing models (ACCESS1, HADGEM-CC and INMCM4) and want to make sure the user is aware of this information.

**Comment by huard** [comment]
Are you referring to the computation of climate indicators ?

**Comment by MatProv** [comment]
> Are you referring to the computation of climate indicators ?

@huard Not really. More about which models are used to provide the ensemble statistics.

**Comment by tlogan2000** [comment]
@aulemahal do you think you could look at this as well seeing as you are already a bit in the finch code?   Can't seem to find time to get to it.   In general the idea is to add a list of input files as an attr to the ensemble percetnile outputs:  I imagine here would be the spot https://github.com/bird-house/finch/blob/6b03e79013dd0ddd2a2e9c32a67f15e6562d8600/finch/processes/ensemble_utils.py#L409

**Comment by tlogan2000** [comment]
Something like this might do the trick ?
````
ensemble_percentiles.attrs['model_list'] = 'List of inputs for ensemble percentiles ;'.join([f.name for f in files])
return ensemble_percentiles
````

**Comment by aulemahal** [comment]
Looks like I'm on a finch week!

**Comment by huard** [comment]
Another pattern would be to include "extra" metadata in an accompanying provenance file, using the PROV standard. 

https://www.sciencedirect.com/science/article/pii/S0098300419306120?via%3Dihub

See http://www.metaclip.org/ for concrete examples. 

This might be too much work for this particular issue, but we could just take the first step of creating a provenance file with a flat list of input model files.

**Comment by aulemahal** [comment]
@huard  @MatProv  What is the timeline for this? I'm asking because PROV looks quite interesting, but a little complex. I want to have an idea on how deep I should dive.
If it's for next week, then it's a pataugeoire and I take Travis' suggestion.

**Comment by MatProv** [comment]
@aulemahal I really don't see this as being urgent. For the portal that's something we would like to have in the next months, but that's not a blocker.

**Comment by huard** [comment]
I'm happy with a temporary solution (e.g. model_list.csv). The PROV approach is something I think we'll want to design from the ground up, not something we hack together. Our colleagues at DKRZ and CEDA are also working on lineage, so can draw from their experience.

**Comment by aulemahal** [comment]
Good. I was reading on PROV this afternoon and, youpelaye, it's complicated. There is a python implementation (https://prov.readthedocs.io), but I believe it's not as extensible as we need it to implement the WPS+PROV scheme from the article you linked.

Also, I believe the METACLIP thing is to specific? All this might need more discussion and exploration.

**Comment by aulemahal** [comment]
I think #182 fixes this. Feel free to re-open if we want a more complete solution.
