### ISSUE TITLE
xclim.core.utils.ValidationError: time series is not recognized as daily

### ISSUE THREAD

**Issue by MatProv** [bird-house/finch#159]
## Description

During execution of process `BCCAQv2_heat_wave_frequency_gridpoint`, we obtain this traceback:

```
Traceback (most recent call last):
  File "/opt/conda/envs/finch/lib/python3.9/site-packages/pywps/app/Process.py", line 248, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/code/finch/processes/wps_base.py", line 37, in _handler_wrapper
    return self.wrapped_handler(request, response)
  File "/code/finch/processes/wps_bccaqv2_heatwave.py", line 155, in _handler
    out = compute_indices(self, self.indices_process.xci, inputs)
  File "/code/finch/processes/utils.py", line 163, in compute_indices
    out = func(**kwds)
  File "/opt/conda/envs/finch/lib/python3.9/site-packages/xclim/core/indicator.py", line 456, in __call__
    self._bind_call(self.datacheck, **das)
  File "/opt/conda/envs/finch/lib/python3.9/site-packages/xclim/core/indicator.py", line 538, in _bind_call
    return func(*ba.args, **ba.kwargs)
  File "/opt/conda/envs/finch/lib/python3.9/site-packages/xclim/core/indicator.py", line 820, in datacheck
    datachecks.check_daily(da)
  File "<boltons.funcutils.FunctionBuilder-115>", line 2, in check_daily
  File "/opt/conda/envs/finch/lib/python3.9/site-packages/xclim/core/options.py", line 98, in run_check
    return _run_check(func, DATA_VALIDATION, *args, **kwargs)
  File "/opt/conda/envs/finch/lib/python3.9/site-packages/xclim/core/options.py", line 90, in _run_check
    raise err
  File "/opt/conda/envs/finch/lib/python3.9/site-packages/xclim/core/options.py", line 83, in _run_check
    func(*args, **kwargs)
  File "/opt/conda/envs/finch/lib/python3.9/site-packages/xclim/core/datachecks.py", line 45, in check_daily
    raise ValidationError("time series is not recognized as daily.")
xclim.core.utils.ValidationError: time series is not recognized as daily.
```

## Environment

* Finch version used, if any: 0.7.0

## Steps to Reproduce

Make a request to finch using these params on bccaqv2 data:

```
"inputs": [
		{
			"id": "lat",
			"data": "45.5837167538"
		},
		{
			"id": "lon",
			"data": "-73.7505505823"
		},
		{
			"id": "thresh_tasmin",
			"data": "16 degC"
		},
		{
			"id": "thresh_tasmax",
			"data": "22 degC"
		},
		{
			"id": "freq",
			"data": "YS"
		},
		{
			"id": "start_date",
			"data":"2000"
		},
		{
			"id":"end_date",
			"data":"2002"
		},
		{
			"id": "output_format",
			"data": "netcdf"
		}
	]
```

**Comment by tlogan2000** [comment]
I have a work around for this somewhere.... one bccaqv2 file is missing a few random days I think

**Comment by tlogan2000** [comment]
````
ds = xr.open_dataset(nc1, chunks=dict(lon=16, lat=16, time=256 * 5))
ds = ds.sel(time=(ds.time.dt.year >= 1950))
if isinstance(ds.time[0].values, np.datetime64):
    date_all = pd.date_range(ds.time[0].values, ds.time[-1].values)
else:
    date_all = xr.cftime_range(ds.time[0].values.item(), ds.time[-1].values.item())
if len(date_all) != len(ds.time):

    ds1 = xr.Dataset(attrs=ds.attrs)
    ds1 = ds1.assign_coords(dict(time=date_all, lat=ds.lat, lon=ds.lon))
    for v in ds.data_vars:
        ds1[v] = ds[v]
    ds = ds1
````

**Comment by tlogan2000** [comment]
Not sure where this all happens in finch though

**Comment by MatProv** [comment]
@huard Can you take a look at this one please? In 0.5.3 we didn't had this, only in 0.7.0.

**Comment by aulemahal** [comment]
Checking and patching on the fly might be complicated because that happens at a point where there is no knowledge of what process was called. Thus, it would be a patch for _everyone_, not only this specific well-known bug.

I agree with 2. But 3 can be an easy fix, specific for that process.

**Comment by tlogan2000** [comment]
I'll try to find which file is causing issues ...

**Comment by aulemahal** [comment]
These are the potential culprits. Finch applies a filter to exclude some of the datasets, I didn't.

https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/pcic/BCCAQv2/tasmin_day_BCCAQv2+ANUSPLIN300_bcc-csm1-1_historical+rcp85_r1i1p1_19500101-21001231.nc is causing difficulties.
https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/pcic/BCCAQv2/tasmin_day_BCCAQv2+ANUSPLIN300_HadGEM2-ES_historical+rcp45_r1i1p1_19500101-21001231.nc is causing difficulties.
https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/pcic/BCCAQv2/tasmin_day_BCCAQv2+ANUSPLIN300_HadGEM2-ES_historical+rcp26_r1i1p1_19500101-21001231.nc is causing difficulties.
https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/pcic/BCCAQv2/tasmin_day_BCCAQv2+ANUSPLIN300_HadGEM2-CC_historical+rcp45_r1i1p1_19500101-21001231.nc is causing difficulties.
https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/pcic/BCCAQv2/tasmax_day_BCCAQv2+ANUSPLIN300_bcc-csm1-1_historical+rcp85_r1i1p1_19500101-21001231.nc is causing difficulties.
https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/pcic/BCCAQv2/tasmax_day_BCCAQv2+ANUSPLIN300_HadGEM2-ES_historical+rcp45_r1i1p1_19500101-21001231.nc is causing difficulties.
https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/pcic/BCCAQv2/tasmax_day_BCCAQv2+ANUSPLIN300_HadGEM2-ES_historical+rcp26_r1i1p1_19500101-21001231.nc is causing difficulties.
https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/pcic/BCCAQv2/tasmax_day_BCCAQv2+ANUSPLIN300_HadGEM2-CC_historical+rcp45_r1i1p1_19500101-21001231.nc is causing difficulties.
https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/pcic/BCCAQv2/pr_day_BCCAQv2+ANUSPLIN300_bcc-csm1-1_historical+rcp85_r1i1p1_19500101-21001231.nc is causing difficulties.
https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/pcic/BCCAQv2/pr_day_BCCAQv2+ANUSPLIN300_HadGEM2-ES_historical+rcp45_r1i1p1_19500101-21001231.nc is causing difficulties.
https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/pcic/BCCAQv2/pr_day_BCCAQv2+ANUSPLIN300_HadGEM2-ES_historical+rcp26_r1i1p1_19500101-21001231.nc is causing difficulties.
https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/pcic/BCCAQv2/pr_day_BCCAQv2+ANUSPLIN300_HadGEM2-CC_historical+rcp45_r1i1p1_19500101-21001231.nc is causing difficulties.

**Comment by aulemahal** [comment]
If we fix them, what fix do we want?
@tlogan2000 's code inserts "NaN" on the missing days.
We could also convert the calendars to the proper ones. I think the datasets are using the default calendars while they were generated from non-standard calendar, this missing some days.

**Comment by tlogan2000** [comment]
I'm not sure but seeing as this is not our data product I would try to keep the data as close to what we received while correcting the times in order to run properly..  Open to other suggestions though

**Comment by aulemahal** [comment]
Ok, suggestion: 
Add option to pass "data_validation" to xclim processes in finch.
Specifically for BCCAQv2 processes, default to "log" (instead of  "raise").
What does @huard think?

**Comment by huard** [comment]
Do you mean hard-coding this option in all BCCAQv2 related processes, or adding is as a user-facing option ?

@MatProv  The call to the process would look something like
```
# determine `data_validation` one way or another...

with xclim.set_options(data_validation=data_validation):
    out = compute_indices(self, self.indices_process.xci, inputs)
```

**Comment by aulemahal** [comment]
Options are already passed, the indicator call looks like : 
https://github.com/bird-house/finch/blob/1c3566badf926c26c68267b5ebe38a0df65ce30e/finch/processes/utils.py#L161-L163

I'm suggesting adding `data_validation` to `INDICATOR_OPTIONS` and setting a different default value in BCCAQv2 things. So user-facing in all cases.

**Comment by tlogan2000** [comment]
This sounds like a promising option to me.  Can we estimate a turnaround time to implement, test and release a new version of Finch?  We are trying to update the analysis page for climatedata.ca with the new version ..

**Comment by aulemahal** [comment]
@tlogan2000  38 min.
Of which at least 15 on the weird signature bug I mention in the PR, which forbid me to test the specific BCCAQv2  process. But the fix works on other xclim indicator processes.

**Comment by MatProv** [comment]
@aulemahal Thanks for the release of 0.7.1. I've tested it this morning and `BCCAQv2_heat_wave_frequency_gridpoint` is now fine. I'm however reopening this issue since i'm having the same issue in `ensemble_grid_point_cold_spell_duration_index`.

**Comment by aulemahal** [comment]
We can discuss this with @huard and @tlogan2000 , but I think _always_ skipping data validation checks is not a good idea overall. My suggestion would be to change the calls to the processes by adding `data_validation='warn'`, only when the `BCCAQv2` datasets are used. Does that make sense?

**Comment by tlogan2000** [comment]
> We can discuss this with @huard and @tlogan2000 , but I think _always_ skipping data validation checks is not a good idea overall. My suggestion would be to change the calls to the processes by adding `data_validation='warn'`, only when the `BCCAQv2` datasets are used. Does that make sense?

I think a web call next week with myself, @aulemahal and @MatProv might be helpful to sort this out.  @huard can include you in the invite too but up to you.  Ok for everyone?
