### ISSUE TITLE
Add notebook demoing polygon averaging

### ISSUE THREAD

**Issue by huard** [bird-house/finch#165]
## Description

Create small notebook using birdy to subset test netCDF dataset hosted on THREDDS.

Question: should we demo using a local hand-made polygon ? local polygon on file ? Polygon from WPS feature ?

**Comment by aulemahal** [comment]
I think we can get by with a remote public polygon?  (From a github or NaturalEarthData)
Or we can go futher and connect to pavics' Geoserver using owslib? (like in my fake example : https://github.com/bird-house/finch/issues/153#issue-817514044)
