### ISSUE TITLE
Failed processes block next ones

### ISSUE THREAD

**Issue by aulemahal** [bird-house/finch#168]
## Description

I was exploring the `average_subset` bug and it failed with a "timeout". However, even when trying again, the finch server keeps failing with a `Service Exception`:

```
ServiceException: <?xml version="1.0" encoding="UTF-8"?>
<!-- PyWPS 4.4.0 -->
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" version="1.0.0">
  <ows:Exception exceptionCode="ServerBusy" locator="" >
      <ows:ExceptionText>Maximum number of parallel running processes reached. Please try later.</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
```

In the log (now readable :rocket: ):
```
2021-03-31 15:45:18,568 - PYWPS - INFO - Request: execute
2021-03-31 15:45:18,580 - PYWPS - INFO - Validating OPeNDAP; Mode: 0
2021-03-31 15:45:18,581 - PYWPS - INFO - validating JSON; Mode: 0
2021-03-31 15:45:18,794 - PYWPS - ERROR - Exception: code: 400, description: Maximum number of parallel running processes reached. Please try later., locator: 
NoneType: None
```

I soupçonne that failed processes are polluting the log and counted as "still running".

## Environment

* Finch version used, if any: branch `fix-logging`
* Operating System: lvupavicsmaster

**Comment by huard** [comment]
Yep, that's a long standing problem... issues are opened on PyWPS and a meeting is planned to find a solution. In the meantime, we need to clean the process DB and restart it. @tlvu

**Comment by huard** [comment]
https://github.com/geopython/pywps/issues/448

**Comment by tlvu** [comment]
> Yep, that's a long standing problem... issues are opened on PyWPS and a meeting is planned to find a solution. In the meantime, we need to clean the process DB and restart it. @tlvu

Gave command to clear pywps queue on my dev VM to @aulemahal already.

**Comment by aulemahal** [comment]
Thanks. I guess we can close this issue then,
