### ISSUE TITLE
average_polygon returns 0 when polygon is outside grid instead of raising error

### ISSUE THREAD

**Issue by huard** [bird-house/finch#179]
## Description

When the shape is outside the grid, average_polygon returns 0. I suggest an error message would be best.

**Comment by Zeitsperre** [comment]
Would it be better to write that behaviour directly into CLISOPS? I feel like this should be the norm.

**Comment by Zeitsperre** [comment]
@huard This will be fixed with `clisops>0.6.3`

**Comment by huard** [comment]
The tox.ini install xesmf from git. Is that really what we want ?
`xesmf: pip install --upgrade git+https://github.com/pangeo-data/xESMF.git`

**Comment by Zeitsperre** [comment]
Perhaps not, but nothing calls it presently. Remove?

**Comment by aulemahal** [comment]
Isn't the reason that tox is using `pip` and  `xesmf` is not available on pip?

**Comment by huard** [comment]
@aulemahal The call goes straight to github, not pypi. 

@Zeitsperre That line was added in your last PR (166).

**Comment by Zeitsperre** [comment]
@huard yes, I know. I added it because I was experiencing issues with my testing environment, but they ended up being due to other libraries being outdated. What I mean is that the CI setup doesn't use it, and it isn't in the documentation, so there's no harm in leaving it there. Remove?

**Comment by aulemahal** [comment]
@Zeitsperre Oh I didn't realize that `tox` is not used in cliops' builds. But doesn't that mean all average_shape tests are skipped as requirements are installed through pip?
I checked quickly and the build for python 3.8 did skip those.

**Comment by Zeitsperre** [comment]
Fixed with https://github.com/roocs/clisops/pull/167
