### ISSUE TITLE
Resample to daily process

### ISSUE THREAD

**Issue by aulemahal** [bird-house/finch#185]
Stumbled upon this problem while writing up the earthcube notebook. 

For a _truly_ remote computation with "arbitrary" data, it would be nice that finch provides some kind of "resampling" process. I am currently thinking a something that would take subdaily inputs and aggregate it to daily using a specific function (min, max, mean, sum). That would allow chain-computations with more datasets!

**Comment by huard** [comment]
Ok, I think this is worth having a design discussion.
