### ISSUE TITLE
Finch instance not accessible using birdy

### ISSUE THREAD

**Issue by huard** [bird-house/finch#19]
## Description

See `docs/source/notebooks/basic.ipynb`

Loading the wps client raises an error. I'm guessing this is due to an older pywps version on the production server.

**Comment by davidcaron** [comment]
It seems to works when I install birdy 0.6.0 from conda. The deployed finch.crim.ca uses the master branch of pywps from a month or 2 ago.

I'll try with the master branch of birdy later today.

Do you have any other idea?

**Comment by huard** [comment]
Does your pywps version include https://github.com/geopython/pywps/pull/464 ?

**Comment by davidcaron** [comment]
No, it's a bit behind at 2a8d9ee4214be574d9c8b6e5b3468d2105a7c1ef
I might redeploy today to add support for bccaqv2 subset, I suggest to not look too much into this until then, as it may fix this when I re-deploy and use a newer pywps.

**Comment by huard** [comment]
Good. My guess is that your PR fixed the issue, so updating will very likely solve it. At least it works here on my end. Let me know when it's done so I can give it a spin.

**Comment by davidcaron** [comment]
I deployed a new version and I think this is fixed. I can launch processes from birdy's master branch. Can you confirm?

**Comment by huard** [comment]
Seems to be working !

**Comment by davidcaron** [comment]
Thanks!
