### ISSUE TITLE
PyWPS 4.4 seems to be complaining about a malformed netCDF

### ISSUE THREAD

**Issue by Zeitsperre** [bird-house/finch#195]
PyWPS 4.4 seems to be complaining about a malformed netCDF, but the output looks fine. The stderr produced is what follows:

> syntax error, unexpected WORD_WORD, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
 > context: <?xml^ version="1.0" encoding="UTF-8"?><ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" version="1.0.0"> <ows:Exception exceptionCode="MissingParameterValue" locator="service" > <ows:ExceptionText>service</ows:ExceptionText> </ows:Exception></ows:ExceptionReport>

_Originally posted by @Zeitsperre in https://github.com/bird-house/finch/issues/189#issuecomment-881673284_

**Comment by huard** [comment]
This is an issue with birdy using a try/except to check if an url can be opened with opendap. This is the message returned by netcdfc when given an url to a PyWPS server with no opendap capability. It's annoying but not a bug per say.
