### ISSUE TITLE
Increase file size limit for average_polygon

### ISSUE THREAD

**Issue by huard** [bird-house/finch#197]
## Description

Increase max file size to 400 Mb. 

## Additional Information

Links to other issues or sources.
https://github.com/Ouranosinc/pavics-sdi/issues/226

**Comment by tlvu** [comment]
Change is located here https://github.com/bird-house/birdhouse-deploy/blob/b9d4ce26c0db89f67b41f5caf7949cc08500feb5/birdhouse/config/finch/wps.cfg.template#L6

**Comment by huard** [comment]
Done with birdhouse-deploy 1.15.1

**Comment by tlvu** [comment]
Link to birdhouse-deploy 1.15.1 PR https://github.com/bird-house/birdhouse-deploy/pull/195
