### ISSUE TITLE
Ability to specify filename prefix and/or suffix

### ISSUE THREAD

**Issue by ldperron** [bird-house/finch#220]
## Description

Is it possible to add an input parameter to allow the user to add some relevant information to the output filename?
For example, when running ensemble_grid_point_* with Average=True leads to files lacking the required info for the user to associate which result goes with which request. For example it will make more sense if the output files names starts with:  "health_region-de-montréal" instead of "ensemble_grid_point".

**Comment by aulemahal** [comment]
As this is web-based and outputs are links, what do you think of:
```python3
import urllib.parse

if query != urllib.parse.quote(query):
    raise...
```

**Comment by ldperron** [comment]
Unfortunately, urllib.parse.quote lets '/' and '.' and '..' go through.
This implementation similar to this one would be perfect (a slugify for filenames):
https://github.com/django/django/blob/4a8ac604b190084aea91c4d627715a833171feca/django/utils/text.py#L224
