### ISSUE TITLE
Feature request: Add RCP column to output when single RCP is selected

### ISSUE THREAD

**Issue by ldperron** [bird-house/finch#229]
## Description

This is a feature request from ECCC. Currently, when a single RCP is selected, it is mentionned within the output file name, but not within the data (netcdf and csv). Is it possible to add it?

**Comment by huard** [comment]
I think I found it: https://github.com/bird-house/finch/blob/e6c1766e043d3235453a73418cf24d4115dd18a3/finch/processes/ensemble_utils.py#L619

**Comment by aulemahal** [comment]
Indeed c'est ça.

Before the multi-rcp thing, there was no "RCP" column. The related PR conserved the previous behaviour for single-rcp requests. This issue seeks to reverse this. I believe a simple `expand_dims` a few lines below what you linked would solve it.

**Comment by huard** [comment]
@ldperron Is this wanted for the ensemble indices computation, the subsets or both ?

**Comment by huard** [comment]
I accidentally pushed to master... argh. 
The concat itself seems to do the work, no?

See https://github.com/bird-house/finch/commit/f23c3837d7a7504061b8ec423f3c09383f33a5aa for the changes.

**Comment by aulemahal** [comment]
Oh indeed, I had not think of doing it that way! I approve this PR ;)

**Comment by perronld** [comment]
It only has been requested for ensemble indices.

Thanks for the change!
