### ISSUE TITLE
More reliable way to identify opendap url

### ISSUE THREAD

**Issue by davidcaron** [bird-house/finch#23]
## Description

Currently, when we want to know if a url is an Opendap url, we append `.dds` to it and check if we get a result.

This causes a problem when sending a link of the following format:

.../thredds/dodsC/birdhouse/nrcan/nrcan_canada_daily_v2/pr/nrcan_canada_daily_pr_2017.nc?pr[0:1:3000][0:1:2][0:1:2]

where appending .dds to the url returns a 404.

We need a more resilient way to find if a url id an opendap url or not.

**Comment by dbyrns** [comment]
You should check this function written by Blaise : https://github.com/Ouranosinc/flyingpigeon/blob/master/flyingpigeon/utils.py#L59

**Comment by davidcaron** [comment]
The problem with doing a try/except is that when the url is not an Opendap url, it takes a second or 2 to raise a IOError. Also, I tried it a while ago and when it's not an opendap url it crashed the interpreter without raising an error... It may have had to do with my installation of netcdf, I'm not sure.

But the netCDF4 library doesn't seem to support constraint expressions, as pointed out by #20.

Knowing the structure of a constraint expression, (it seems to be located only in query parameters) we can still use the technique of appending any standard opendap suffix to the url (.dds, .das, .ver, ...) by removing the query string. But that url will still be passed to xarray or netcdf4, and it won't work unless we implement #20. So these 2 issues are related.

**Comment by huard** [comment]
Got bit by this recently. Can it be dealt with client-side ? The client could then pass the mimetype of the input, and then we would not have to guess server-side.

**Comment by davidcaron** [comment]
What was the url you sent to the server?

**Comment by davidcaron** [comment]
I did a quick research, and I think that if we make a HEAD request to the url, the `Content-Description` header should always start with `dods` if it's an opendap url.

Check the section 7.1.1 at: https://www.opendap.org/pdf/ESE-RFC-004v1.2.pdf

**Comment by huard** [comment]
It was a THREDDS DAP url but starting with http. I had to write href=http... for pywps to recognize it as URL and not as data, but that may be a quirk of pywps.
