### ISSUE TITLE
Feature request: Add output_format parameter for processes

### ISSUE THREAD

**Issue by perronld** [bird-house/finch#231]
## Description

For the Analysis on AHCCD stations data, we need to be able to provide csv and netcdf output format for xclim indicators processes. Currently, only netcdf is provided.

**Comment by tlogan2000** [comment]
@huard  do you think it would be possible to add a `output_format` option for .csv in the finch indicator calculations?

**Comment by aulemahal** [comment]
I'm trying this at the moment. This implies renaming the output field from `output_netcdf` to `output`, which format can be a "netCDF" (same as before) or a "zip" (with the csv and the metadata txt).
