### ISSUE TITLE
csv_precision not working as expected

### ISSUE THREAD

**Issue by perronld** [bird-house/finch#263]
## Description

When specifying csv_precision, the generated file doesn't reflect the requested csv_precision. For example, with ensemble_grid_point_wetdays, if I request a csv_precision of 5, I obtain a csv file with 1 decimal.

## Environment

* Finch version used, if any: v0.10.0

## Additional Information

The reason of this behavior, is that the usage of Numpy's round keeps the data within the same format (float stays float, double stays double). Instead, the float_format parameter of dataframe.to_csv() could be used, as I propose here: https://github.com/bird-house/finch/tree/float_format

**Comment by aulemahal** [comment]
Indeed. Would you like this in a release soon? I'll use your suggestion and I will add tests.

**Comment by perronld** [comment]
No need to haste a release only for this issue, I deployed this branch directly to our staging environment

**Comment by perronld** [comment]
CCCS found out that my float_format fix was causing issues with lat/lon having their decimals dropped. I used a new strategy in https://github.com/bird-house/finch/commit/87bf652e2f31db5ea3c5e32e44318e4a702c1df1

**Comment by tlogan2000** [comment]
@perronld Do we want to open a PR for these changes and get them merged to the main branch?
