### ISSUE TITLE
What kind of bird is Finch?

### ISSUE THREAD

**Issue by Zeitsperre** [bird-house/finch#288]
README: "_Finch is a bird..._"

This has been bothering me for years. We need some metaphor / definition.

**Comment by Zeitsperre** [comment]
"Finch is a bird that can adapt to many different climates and ecological niches" ?

**Comment by aulemahal** [comment]
Well. Might be true for the finch bird, but I'm not sure it correctly applies to this repo :sweat: !

**Comment by Zeitsperre** [comment]
I just figured that there's a connection to climate (xclim) and the finch bird. I'm just spitballing here!
