### ISSUE TITLE
Distinct models should have distinct columns in CSV output

### ISSUE THREAD

**Issue by perronld** [bird-house/finch#311]
## Description

When executing ensemble process with an empty string for "ensemble_percentiles", if the requested output is CSV, individual model should have their own columns, instead of a single column for the result, and an additional column for realization. This will make the resulting CSV file directly useable for spreadsheet and graphing.

## Environment

* Finch version used, if any: commit 546b0e600aad56112129f98dac781b37817511a9

Links to other issues or sources: https://ccdpwiki.atlassian.net/browse/CLIM-380

**Comment by aulemahal** [comment]
Should be an easy case of `df.pivot_table`.
