### ISSUE TITLE
Incorrect output in `finch-usage` notebook

### ISSUE THREAD

**Issue by fmigneault** [bird-house/finch#347]
## Description

Notebook https://github.com/bird-house/finch/blob/master/docs/source/notebooks/finch-usage.ipynb
The cell output URL displays: 
```
Link to process output:  /e353412c-c695-11ee-a6f6-484d7ef8da38/frost_days_sres_a2_experiment_20460101_20650101.nc
```
However, it seems the full URL is returned when actually running the notebook, causing a diff error by nb val.

```
Link to process output:  https://wps_host/wpsoutputs/STATUS_FILE/frost_days_sres_a2_experiment_20460101_20650101.nc
```

## Environment

* Finch version used, if any:
  https://github.com/bird-house/birdhouse-deploy/blob/8218166d5c8c7163293a656930ff85762eff4b60/birdhouse/components/finch/default.env#L7-L8
* Python version, if any: whichever one resolved by https://github.com/bird-house/finch/blob/master/Dockerfile
* Operating System: docker

## Steps to Reproduce

Any birdhouse-deploy PR that triggers the CI fails with: 
```
[2024-03-13T15:07:35.217Z] finch-master/docs/source/notebooks/dap_subset.ipynb ...........          [ 76%]
[2024-03-13T15:07:44.892Z] finch-master/docs/source/notebooks/finch-usage.ipynb ...F..              [ 78%]
```

```
11:12:38  _________ finch-master/docs/source/notebooks/finch-usage.ipynb::Cell 3 _________
11:12:38  Notebook cell execution failed
11:12:38  Cell 3: Cell outputs differ
11:12:38  
11:12:38  Input:
11:12:38  print("Process status: ", resp.status)
11:12:38  urls = resp.get()
11:12:38  print("Link to process output: ", urls.output)
11:12:38  
11:12:38  Traceback:
11:12:38   mismatch 'stdout'
11:12:38  
11:12:38   assert reference_output == test_output failed:
11:12:38  
11:12:38    'Process stat...20650101.nc\n' == 'Process stat...20650101.nc\n'
11:12:38    Skipping 49 identical leading characters in diff, use -v to show
11:12:38    -  output:  https://wps_host/wpsoutputs/STATUS_FILE/frost_days_sres_a2_experiment_20460101_20650101.nc
11:12:38    ?           ---------------------------
11:12:38    +  output:  /STATUS_FILE/frost_days_sres_a2_experiment_20460101_20650101.nc
```

## Additional Information

n/a

**Comment by tlvu** [comment]
@Zeitsperre can you take a look at this one.  Could the a problem with the `make refresh-notebook` target.  Maybe the `Makefile` changes recently with all the cookiecutter refreshes.

**Comment by tlvu** [comment]
Notebook fix here https://github.com/bird-house/finch/pull/348 just to get Jenkins to pass.  We still have to find and fix the root-cause so it does not happen again on the next output refresh.

**Comment by fmigneault** [comment]
PR #348 looks fine. 
Will close this issue for now,.
If anything doesn't work in the CI, will reopen later.
