### ISSUE TITLE
Ouranos deployment has configuration problem

### ISSUE THREAD

**Issue by huard** [bird-house/finch#35]
## Description
Running `finch.ipynb` in `xclim/docs/notebooks/xclim_training` returns a link to output files at `localhost` instead of `pavics.ouranos.ca`. The output files of course cannot be found at that address. 

```
ProcessSucceeded
frost_daysResponse(
    output_netcdf='http://localhost:5000/outputs/e435307c-7bc8-11e9-9d55-0242ac120017/out.nc',
    output_log='http://localhost:5000/outputs/e435307c-7bc8-11e9-9d55-0242ac120017/log.txt'
)
```

**Comment by tlvu** [comment]
This has been fixed and deployed to prod via PR https://github.com/Ouranosinc/PAVICS/pull/122
