### ISSUE TITLE
`unidecode` is under GPLv2

### ISSUE THREAD

**Issue by Zeitsperre** [bird-house/finch#358]
## Description

`unidecode` is used in several processes and, unfortunately, is not technically allowed to be integrated into this project due to incompatible licenses. This library needs to be removed and replaced.

## Additional Information

https://www.apache.org/licenses/GPL-compatibility.html

**Comment by fmigneault** [comment]
Flagged for example in https://app.fossa.com/projects/git%2Bgithub.com%2Fbird-house%2Ffinch/refs/branch/master/e932ac77677517554960ecc428d2ca6d6fc007e7/preview

@Zeitsperre 
Interesting license checker! 
Is it enabled for other birds repositories as well?

**Comment by Zeitsperre** [comment]
@fmigneault The free version is limited to 5 repositories by person. I have this enabled in a few major repos, so unfortunately I can't add any more. Perhaps you can make an account and add a few?

The cost of the paid version is exorbitant (5 users and unlimited repos = +$300/mo).

**Comment by fmigneault** [comment]
@Zeitsperre Yes. I did exactly that :) I've added Weaver so far. Will add others according to their relevance for the project.
