### ISSUE TITLE
Multiple grid cells when subsetting

### ISSUE THREAD

**Issue by davidcaron** [bird-house/finch#56]
## Description

There is a need to subset the BCCAQv2 data with multiple grid cells at a time. Not a bounding box, just a list of lat-lon coordinates.

@huard I was wondering how we should implement this and I wanted to get your opinion. Here is how I could do it. Currently, the `SubsetBCCAQV2Process` process accepts lat0, lat1, lon0, lon1 coordinates. If the lat1 and lon1 are not given, the process makes a single grid cell subset. 

I was thinking of changing the lon0 and lat0 to accept a list of comma separated floats instead. Do you think this would be confusing? So the same process could be used for:

- Single grid cell subset: lat0, lon0
- Boundingbox subset: lat0, lon0, lat1, lon1
- Multiple grid cell subset: lat0, lon0 as a list of comma separated floats

**Comment by huard** [comment]
I think you can probably use the same interface for single and multiple grid cell subsets. 
I would keep the bounding box interface separate.
