### ISSUE TITLE
subset_ensemble_bccaqv2 parameters 

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/finch#74]
## Description

There are the parameters `variable : {'tasmin', 'tasmax', 'pr'}`
Whats about others? e.g. `tas`?
suggestion use `get_variable` in  `eggshhell.nc.nc_utils` 

for `rcp : {'rcp26', 'rcp45', 'rcp85'}`
What about `rcp60`, `historical` and `evaluation`?

Also suggestion to use eggshells `sort_by_filename` which is brining files belonging to one dataset together

**Comment by aulemahal** [comment]
Closing this because it seems to have become irrelevant. The BCCAQV2-specific subset processes will be removed in 0.9.0.

Moreover, the reason for those missing rcps is simply that they don't exist in BCCAQv2.

2.5 years.. It's a long time to wait, only to be told no. Sorry!
