### ISSUE TITLE
Add units to inputs for process descriptions

### ISSUE THREAD

**Issue by davidcaron** [bird-house/finch#90]
## Description

Some inputs have units that could be described in the DescribeProcess document. For example temperature (degC) or precipitations (mm/day). These could be used for default units when not provided. @huard what do you think?

Also, these units can be used by the platform frontend. Currently, the only way I'm aware of to know which unit to provide to the process is by parsing the default values...

Related PR: https://github.com/geopython/pywps/pull/523

**Comment by huard** [comment]
I think this is a necessary improvement.

**Comment by huard** [comment]
@aulemahal Since we're now enforcing string values including units, I suggest we close this.

**Comment by aulemahal** [comment]
Agrred.
