### ISSUE TITLE
Add processes and inputs metadata internationalization

### ISSUE THREAD

**Issue by davidcaron** [bird-house/finch#94]
## Description

Related to https://github.com/Ouranosinc/xclim/pull/359

**Comment by Zeitsperre** [comment]
@davidcaron we just tagged and released v0.15.0 which integrates the necessary changes. The conda feedstock will update in a few hours. I'll post again when it's available.

**Comment by Zeitsperre** [comment]
Conda package is now up. Feel free to proceed.
